.github/workflows/ci.yml
build.gradle.kts

https://github.com/openrewrite/rewrite/issues/324

skip snapshot gpg signing by default unless opt-in

---

src/main/resources/META-INF/rewrite/spring-boot2.yml

Update SpringBoot1To2Migration per associated JUnit5 recipe changes

Update SpringBoot1To2Migration recipe list

---

src/main/java/org/openrewrite/java/spring/BeanMethodsNotPublic.java

Stylistic, but, invert BeanMethodsNotPublic visitMethodDeclaration to have single return

Invert BeanMethodsNotPublic visitMethodDeclaration to have single return

---

src/main/java/org/openrewrite/java/spring/MaybeAddJavaxValidationDependencies.java
src/main/java/org/openrewrite/java/spring/boot2/UnnecessarySpringExtension.java

Polish UnnecessarySpringExtension and MaybeAddSpringValidationVisitor with statics

---

build.gradle.kts
src/main/java/org/openrewrite/java/spring/boot2/OutputCaptureExtension.java

This branch will not build until this parameterized-types branch in rewrite-core has been merged.

Parameterized Types

---

src/main/resources/META-INF/rewrite/spring-boot2-upgrade-version.yml
src/main/resources/META-INF/rewrite/spring-boot2.yml

Moved 1.x to 2.0 migration out of 1.x to 2.x. Added UpgradeSpringBoot_2_5 to 1.x to 2.x.

---

src/main/java/org/openrewrite/java/spring/boot2/MigrateLoggingSystemPropertyConstants.java
src/main/java/org/openrewrite/java/spring/boot2/ReplaceDeprecatedEnvironmentTestUtils.java

Co-authored-by: Moderne <team@moderne.io>

refactor: Remove unused imports

---

src/main/resources/META-INF/rewrite/spring-boot-configuration-migration.yml

see: https://github.com/openrewrite/rewrite-spring/issues/97
Changes for `spring.datasource.*`-related keys.

SB2.5.x property key changes for spring.datasource configs

---

src/main/resources/META-INF/rewrite/spring-boot-configuration-migration.yml

Closes https://github.com/openrewrite/rewrite-spring/issues/97
Keeping as separate PRs for git history.

SB2.5 property keys for artemis and batch

---

src/main/java/org/openrewrite/java/spring/YamlPropertiesToKebabCase.java
src/test/kotlin/org/openrewrite/java/spring/YamlPropertiesToKebabCaseTest.kt

Part of https://github.com/openrewrite/rewrite-spring/issues/112

Normalize Spring properties to use lowercase kebab case

---

src/main/java/org/openrewrite/java/spring/boot2/search/LoggingShutdownHooksRecipe.java
src/test/kotlin/org/openrewrite/java/spring/boot2/search/LoggingShutdownHooksRecipeTest.kt

@fabapp2 initial implementation marking the maven project
Fixes #141

Logging Shutdown Hook recipe initial impl

---

build.gradle.kts
src/main/java/org/openrewrite/java/spring/boot2/search/IntegrationSchedulerPoolRecipe.java

- Pin okhttp version to 4.x (as https://github.com/openrewrite/rewrite/commit/481cacb8cd41c22448b83f6d6ab7a0d3d24419c0)
- ListUtils replacing ArrayList

Pin okhhtp version to 4.x. Review feedback

---

build.gradle.kts

Somehow a typo lurked into my previous fix.

Fix typo in the version

---

.gitignore
src/main/resources/META-INF/rewrite/spring-boot2-upgrade-version.yml

Fixes #190
Relates to https://github.com/spring-projects/spring-boot/issues/29589

2.7+ Migration: ChangeType on moved @Local*Port annotations

---

build.gradle.kts
src/testWithSpringBoot_2_4/kotlin/org/openrewrite/java/spring/boot2/UnnecessarySpringExtensionTest.kt

Add test case for SpringBatchTest

---

build.gradle.kts
src/main/java/org/openrewrite/java/spring/AddSpringProperty.java
src/main/java/org/openrewrite/java/spring/ChangeSpringPropertyKey.java
src/main/java/org/openrewrite/java/spring/DeleteSpringProperty.java
src/main/java/org/openrewrite/java/spring/YamlPropertiesToKebabCase.java
src/main/java/org/openrewrite/java/spring/boot2/DatabaseComponentAndBeanInitializationOrdering.java
src/main/java/org/openrewrite/java/spring/boot2/MigrateActuatorMediaTypeToApiVersion.java
src/main/java/org/openrewrite/java/spring/boot2/MigrateDatabaseCredentials.java
src/main/java/org/openrewrite/java/spring/boot3/PreciseBeanType.java
src/main/java/org/openrewrite/java/spring/framework/MigrateWebMvcConfigurerAdapter.java
src/main/java/org/openrewrite/maven/spring/UpgradeExplicitSpringBootDependencies.java
suppressions.xml

Reverts openrewrite/rewrite-spring#238

Revert "chore: update jackson"

---

src/main/resources/META-INF/rewrite/spring-boot-30.yml

Recipes name/id changed in **rewrite-migrate-java** but reference not adjusted in **rewrite-spring**

Reference proper Java 17 upgrade recipe

---

src/main/java/org/openrewrite/java/spring/AutowiredFieldIntoConstructorParameterVisitor.java
src/testWithSpringBoot_2_1/java/org/openrewrite/java/spring/AutowiredFieldIntoConstructorParameterVisitorTest.java

Addendum to Autowired field into constructor parameter visitor

Correct prefix for the first modifier

---

src/main/resources/META-INF/rewrite/spring-boot-30.yml

Include Auto-config recipe in Boot 3 upgrade

Include auto-config into Boot 3 upgrade

---

src/main/resources/META-INF/rewrite/spring-boot-27.yml
src/testWithSpringBoot_2_7/java/org/openrewrite/java/spring/boot2/UpdateMysqlDriverArtifactIdTest.java

Update MySQL Driver artifactId & version number

---

build.gradle.kts
src/main/java/org/openrewrite/java/spring/boot3/ConfigurationOverEnableSecurity.java
src/main/resources/META-INF/rewrite/spring-boot-30.yml
src/testWithSpringBoot_2_4/java/org/openrewrite/java/spring/boot2/ConfigurationOverEnableSecurityTest.java
src/testWithSpringBoot_3_0/java/org/openrewrite/java/spring/boot3/ConfigurationOverEnableSecurityTest.java

See [Add @Configuration annotation](https://docs.spring.io/spring-security/reference/5.8/migration/servlet/config.html#add-configuration-annotation)

EnableSecurity annotations need @Configuration in boot 3

---

build.gradle.kts
src/main/java/org/openrewrite/java/spring/boot2/AuthorizeHttpRequests.java
src/testWithSpringBoot_2_7/java/org/openrewrite/java/spring/boot2/AuthorizeHttpRequestsTest.java

See [Authorize HttpServletRequests with AuthorizationFilter](https://docs.spring.io/spring-security/reference/servlet/authorization/authorize-http-requests.html)
- `authorizeRequest` -> `authorizeHttpRequests`
- `ExpressionInterceptUrlRegistry` -> `AuthorizationManagerRequestMatcherRegistry`
- `ExpressionUrlAuthorizationConfigurer` -> `AuthorizeHttpRequestsConfigurer`
- `AbstractInterceptUrlConfigurer` -> `AuthorizeHttpRequestsConfigurer`

Security - authorizeHttpRequests

---

src/main/java/org/openrewrite/java/spring/boot2/WebSecurityConfigurerAdapter.java
src/testWithSpringBoot_2_4/java/org/openrewrite/java/spring/boot2/WebSecurityConfigurerAdapterTest.java

Handled the case from [WebSecurityConfigurerAdapter Gone](https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter) **In-Memory Authentication** section

WebSecurityConfigurerAdapter - In-Memory Auth

---

src/testWithSpringBoot_2_7/java/org/openrewrite/java/spring/boot2/UpdateMysqlDriverArtifactIdTest.java

New boot patch version became available: 2.7.9

Fix unit test

---

src/testWithSpringBoot_2_7/java/org/openrewrite/java/spring/boot2/UpdateMysqlDriverArtifactIdTest.java

@timtebeek it was easy to implement a better fix for the test with the pointer you've provided. You merged the previous PR a minute ahead I updated the branch :-)

Better fix for the test

---

src/main/java/org/openrewrite/java/spring/security5/UseNewRequestMatchers.java
src/main/java/org/openrewrite/java/spring/security6/PropagateAuthenticationServiceExceptions.java
src/main/resources/META-INF/rewrite/spring-security-60.yml
src/testWithSpringSecurity_5_8/java/org/openrewrite/spring/security6/PropagateAuthenticationServiceExceptionsTest.java

See https://docs.spring.io/spring-security/reference/6.0.0/migration/servlet/authentication.html#_propagate_authenticationserviceexceptions for details.
Related: #256

Remove calls matching `AuthenticationEntryPointFailureHandler.setRethrowAuthenticationServiceException(true)`

---

src/main/resources/META-INF/rewrite/spring-boot-30.yml

Retain versions for thymeleaf-spring5 & thymeleaf-extras-springsecurity5

---

src/test/java/org/openrewrite/java/spring/RecipeDescriptorTest.java

Tests Boot 3 upgrade recipe descriptor

---

src/main/java/org/openrewrite/java/spring/ChangeSpringPropertyValue.java
src/main/resources/META-INF/rewrite/spring-boot-20.yml
src/test/java/org/openrewrite/java/spring/ChangeSpringPropertyValueTest.java

fixes #329
depends on https://github.com/openrewrite/rewrite/pull/3103

introduced ChangeSpringPropertyValue

---

src/test/java/org/openrewrite/java/spring/cloud2022/MigrateProjectTest.java

fixing test case in response to rewrite#3268

---

README.md
src/main/java/org/openrewrite/java/spring/internal/SpringBootReleases.java
src/main/resources/META-INF/rewrite/spring-boot-21.yml
src/main/resources/META-INF/rewrite/spring-boot-22.yml
src/main/resources/META-INF/rewrite/spring-boot-23.yml
src/main/resources/META-INF/rewrite/spring-boot-26.yml
src/main/resources/META-INF/rewrite/spring-boot-30.yml
src/main/resources/META-INF/rewrite/spring-boot-31.yml
src/test/java/org/openrewrite/java/spring/GeneratePropertiesMigratorConfiguration.java

Partial fix for #357 and in response to #356

Regenerate property migrations

---

src/main/java/org/openrewrite/java/spring/boot2/search/EntityIdForRepositoryVisitor.java
src/testWithSpringBoot_2_4/java/org/openrewrite/java/spring/boot2/search/EntityIdForRepositoryVisitorTest.java

The visitor to be used to mark validation problems in Spring Data Repo interfaces. See https://github.com/spring-projects/sts4/issues/457

Spring Data Repo domain type id validation search visitor

---

src/main/resources/META-INF/rewrite/spring-boot-31.yml

The base for Boot 3.1 upgrade.
Pom upgrade. Aggregate recipe with Pom and properties upgrade recipes.

Basic Boot 3.1 Upgrade

---

src/main/java/org/openrewrite/java/spring/AddSpringProperty.java

The current example is incorrect as a list will need to be in `[]` I'm pretty sure. Related PR: https://github.com/openrewrite/rewrite-docs/pull/195/files

Update AddSpringProperty.java example

---

build.gradle.kts
src/main/java/org/openrewrite/java/spring/boot2/ConvertToSecurityDslVisitor.java
src/testWithSpringBoot_2_4/java/org/openrewrite/java/spring/boot2/HttpSecurityLambdaDslTest.java
src/testWithSpringBoot_2_4/java/org/openrewrite/java/spring/boot2/ServerHttpSecurityLambdaDslTest.java

`disable` is similar to `and` with the important difference that it should be _included_ rather than _excluded_ from the chain.
@BoykoAlex @nmck257 @timtebeek

`disable` is a terminal function

---

src/main/java/org/openrewrite/java/spring/ChangeSpringPropertyKey.java
src/main/resources/META-INF/rewrite/spring-boot-22.yml
src/test/java/org/openrewrite/java/spring/ChangeSpringPropertyKeyTest.java

fixes #432

---

src/test/java/org/openrewrite/java/spring/cloud2022/MigrateCloudSleuthToMicrometerTracingTest.java
src/test/java/org/openrewrite/java/spring/cloud2022/MigrateProjectTest.java
src/testWithSpringBoot_1_5/java/org/openrewrite/java/spring/boot2/MigrateToWebServerFactoryCustomizerTest.java
src/testWithSpringBoot_2_3/java/org/openrewrite/java/spring/boot2/AddsStarterValidationTest.java
src/testWithSpringBoot_2_3/java/org/openrewrite/java/spring/boot2/SpringBoot2JUnit4to5MigrationTest.java
src/testWithSpringBoot_2_4/java/org/openrewrite/java/spring/boot2/SpringProfilesGroupPropertyTest.java
src/testWithSpringBoot_2_4/java/org/openrewrite/java/spring/boot2/UpgradeDependenciesTest.java
src/testWithSpringBoot_2_4/java/org/openrewrite/java/spring/boot2/UpgradeSpringBoot2ConfigurationTest.java
src/testWithSpringBoot_2_7/java/org/openrewrite/gradle/spring/UpdateGradleTest.java
src/testWithSpringBoot_2_7/java/org/openrewrite/java/spring/boot2/UpdateMysqlDriverArtifactIdTest.java
src/testWithSpringBoot_2_7/java/org/openrewrite/java/spring/http/ReplaceLiteralsTest.java
src/testWithSpringBoot_3_0/java/org/openrewrite/java/spring/boot3/UpgradeSpringBoot3ConfigurationTest.java
src/testWithSpringSecurity_5_7/java/org/openrewrite/spring/security5/ReplaceGlobalMethodSecurityWithMethodSecurityTest.java
src/testWithSpringSecurity_5_8/java/org/openrewrite/spring/security5/RenameNimbusdsJsonObjectPackageNameTest.java

We're seeing frequent OutOfMemoryErrors with ClassGraph; hoping this helps.

Limit scanned packages

---

src/main/java/org/openrewrite/java/spring/http/ReplaceStringLiteralsWithMediaTypeConstants.java

Fixed compilation errors

---

src/main/resources/META-INF/rewrite/spring-security-62.yml

A recipe for Spring Security 6.2 (RC for now)
To prepare the infrastructure for Spring Boot 3.2

feat: spring-security-62.yml

---

src/main/resources/META-INF/rewrite/spring-boot-32.yml

Swapped out deprecated classes to preempt Spring Boot 3.3 issues.
To preempt issues with Spring Boot 3.3
@timtebeek 
Contributes to #450

feat: swap out deprecated classes for Spring Boot 3.2

---

src/main/java/org/openrewrite/java/spring/AddSpringProperty.java
src/main/java/org/openrewrite/java/spring/boot2/MigrateDatabaseCredentials.java

Resolved build issues related  to new addProperty signature
to resolve build issues

fix: fix issues related to new addProperty signature

---

src/main/java/org/openrewrite/java/spring/AddSpringProperty.java
src/main/java/org/openrewrite/java/spring/boot2/MigrateDatabaseCredentials.java
src/test/java/org/openrewrite/java/spring/AddSpringPropertyTest.java
src/test/java/org/openrewrite/java/spring/cloud2022/AddLoggingPatternLevelForSleuthTest.java

Use the updated recipe from from https://github.com/openrewrite/rewrite/pull/3771

`AddSpringProperty` now add comments to application.properties files

---

build.gradle.kts
src/testWithSpringBoot_3_2/java/org/openrewrite/java/spring/boot3/.editorconfig
src/testWithSpringBoot_3_2/java/org/openrewrite/java/spring/boot3/EnableVirtualThreadsTest.java

Replicate ClassCastException in EnableVirtualThreads following
- #446 
Bug reported via Slack.

Replicate ClassCastException in EnableVirtualThreads

---

src/testWithSpringBoot_3_2/java/org/openrewrite/java/spring/boot3/EnableVirtualThreadsTest.java

Should be fixed after https://github.com/openrewrite/rewrite/commit/38f3cfdb805ebeb30105ba469dc7dc67e6328ad0

Run EnableVirtualThreadsTest again

---

src/main/resources/META-INF/rewrite/spring-boot-32.yml

The getting started page still used Spring Boot 2 best practices
Things have migrated to Spring Boot 3 :).

Add Spring Boot 3 best practices

---

src/main/resources/META-INF/rewrite/spring-boot-22.yml

Fixes https://github.com/openrewrite/rewrite-spring/issues/472
- https://docs.spring.io/spring-boot/docs/2.2.0.RELEASE/api/org/springframework/boot/test/rule/OutputCapture.html
- https://docs.spring.io/spring-boot/docs/2.2.0.RELEASE/api/org/springframework/boot/test/system/OutputCaptureRule.html

Replace OutputCapture with OutputCaptureRule in 2.2

---

src/test/java/org/openrewrite/java/spring/AddSpringPropertyTest.java
src/testWithSpringBoot_2_4/java/org/openrewrite/java/spring/boot2/MigrateDatabaseCredentialsTest.java

Following https://github.com/openrewrite/rewrite/compare/1a9289a12573c71a636e568a41c664956eaaa4e6...1124e3d3c168ad396052224e8eabad0492318967

Expect new spring property keys to be sorted

---

src/main/java/org/openrewrite/java/spring/boot3/AddRouteTrailingSlash.java
src/main/java/org/openrewrite/java/spring/security5/ReplaceGlobalMethodSecurityWithMethodSecurity.java
src/testWithSpringBoot_2_7/java/org/openrewrite/java/spring/boot2/AddRouteTrailingSlashTest.java
src/testWithSpringSecurity_5_7/java/org/openrewrite/spring/security5/ReplaceGlobalMethodSecurityWithMethodSecurityTest.java

Remove deprecated code in place for new functionality.
https://github.com/openrewrite/rewrite/issues/3754#issuecomment-1850988722
Is not a complete implementation due to time constraints, will be able to complete any final changes as needed. Not tested with build.
@timtebeek
N/A
N/A
- [ No] I've added unit tests to cover both positive and negative cases
- [ No] I've read and applied the [recipe conventions and best practices](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices)
- [No ] I've used the IntelliJ IDEA auto-formatter on affected files

Fully remove part provider and last remaining references

---

src/main/java/org/openrewrite/java/spring/RenameBean.java

Use this link to re-run the recipe: https://app.moderne.io/recipes/builder/XkVt46WER?organizationId=T3BlblJld3JpdGU%3D

refactor: Recipe nullability best practices

---

src/main/java/org/openrewrite/java/spring/boot2/DatabaseComponentAndBeanInitializationOrdering.java

Fixes https://github.com/openrewrite/rewrite-spring/issues/504
@timo-abele

Skip `SpringLiquibase` in `DatabaseComponentAndBeanInitializationOrdering`

---

src/main/resources/META-INF/rewrite/spring-boot-30.yml

Added property change from management.metrics.export.atlas.aggrConfig to management.atlas.metrics.export.aggrConfig in UpgradeSpringBoot_3_0
Just noticed from personal experience this property change was missing in the recipe 🙂

Add property change from management.metrics.export.atlas.aggrConfig to management.atlas.metrics.export.aggrConfig in UpgradeSpringBoot_3_0 recipe

---

build.gradle.kts
src/main/resources/META-INF/rewrite/spring-boot-33.yml

Follows
- https://github.com/openrewrite/rewrite-spring/pull/551
- https://github.com/openrewrite/rewrite-spring/commit/3edc1e0e45edf7e66b72435b2380aac1371bb49e
- https://github.com/openrewrite/rewrite-micrometer/pull/13

Upgrade Micrometer 1.13 as part of Spring Boot 3.3

---

build.gradle.kts
src/main/java/org/openrewrite/java/spring/data/RefactorSimpleMongoDbFactory.java
src/main/resources/META-INF/rewrite/spring-data-23.yml
src/testWithSpringBoot_2_3/java/org/openrewrite/java/spring/data/RefactorSimpleMongoDbFactoryTest.java

Added a few refactoring steps related to mongoDb including a testcase
@timtebeek 
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes#spring-data-neumann
https://spring.io/blog/2020/05/18/what-s-new-in-spring-data-klara-dan-von-neumann
https://docs.spring.io/spring-data/mongodb/docs/3.0.0.RELEASE/reference/html/#upgrading.2-3

Add recipes for MongoDb related changes in Spring Boot/Data 2.3

---

build.gradle.kts
suppressions.xml

Related to: https://github.com/moderneinc/dependency-vulnerability-reports/issues/741

update to latest error prone to remove protobuf-java@3.19.2 vulnerability

---

src/main/java/org/openrewrite/java/spring/batch/MigrateJobBuilderFactory.java
src/main/java/org/openrewrite/java/spring/batch/MigrateStepBuilderFactory.java
src/main/java/org/openrewrite/java/spring/batch/RemoveDefaultBatchConfigurer.java
src/main/java/org/openrewrite/java/spring/batch/ReplaceSupportClassWithItsInterface.java
src/main/java/org/openrewrite/java/spring/boot3/RemoveConstructorBindingAnnotation.java
src/main/java/org/openrewrite/java/spring/framework/HttpComponentsClientHttpRequestFactoryReadTimeout.java
src/main/java/org/openrewrite/java/spring/framework/MigrateWebMvcConfigurerAdapter.java
src/main/java/org/openrewrite/java/spring/security6/PropagateAuthenticationServiceExceptions.java
src/main/java/org/openrewrite/java/spring/security6/UseSha256InRememberMe.java
src/main/java/org/openrewrite/java/spring/test/SpringRulesToJUnitExtension.java
src/main/resources/TestPropertyValues.java

Use this link to re-run the recipe: https://app.moderne.io/builder/ji8mLIdUI?organizationId=T3BlblJld3JpdGU%3D

refactor: add @Nullable to methods who may return null

---

suppressions.xml

Removing suppressions which no longer apply and adding suppressions which need to be suppressed

Updating Suppressions

---

build.gradle.kts
src/main/resources/META-INF/rewrite/spring-boot-31.yml

For https://github.com/openrewrite/rewrite-recipe-bom/pull/36#issuecomment-2593383428
- https://github.com/openrewrite/rewrite-spring/pull/564

Drop reactive streams recipes

---

src/main/java/org/openrewrite/java/spring/ExpandProperties.java
src/main/resources/META-INF/rewrite/spring-boot-20.yml
src/main/resources/META-INF/rewrite/spring-boot-21.yml
src/main/resources/META-INF/rewrite/spring-boot-22.yml
src/main/resources/META-INF/rewrite/spring-boot-23.yml
src/main/resources/META-INF/rewrite/spring-boot-24.yml
src/main/resources/META-INF/rewrite/spring-boot-25.yml
src/main/resources/META-INF/rewrite/spring-boot-26.yml
src/main/resources/META-INF/rewrite/spring-boot-27.yml
src/main/resources/META-INF/rewrite/spring-boot-30.yml
src/main/resources/META-INF/rewrite/spring-boot-32.yml

Introduce recipes that upgrade MyBatis Spring Boot components along with SpringBoot version upgrades
@timtebeek 
- https://github.com/mybatis/spring-boot-starter

Add mybatis upgrades across spring versions

---

src/main/java/org/openrewrite/java/spring/AddSpringProperty.java
src/main/java/org/openrewrite/java/spring/boot2/MergeBootstrapYamlWithApplicationYaml.java
src/main/java/org/openrewrite/java/spring/boot2/MigrateDatabaseCredentials.java

Update MergeYaml constructors
- https://github.com/openrewrite/rewrite/pull/5036

Update MergeYaml constructors

---

src/main/java/org/openrewrite/java/spring/framework/MigrateMethodArgumentNotValidExceptionErrorMethod.java
src/main/java/org/openrewrite/java/spring/framework/MigrateResourceHttpMessageWriterAddHeadersMethod.java
src/main/java/org/openrewrite/java/spring/framework/MigrateUriComponentsBuilderMethods.java
src/main/java/org/openrewrite/java/spring/framework/MigrateWebExchangeBindExceptionResolveErrorMethod.java
src/main/resources/META-INF/rewrite/spring-framework-62.yml
src/test/java/org/openrewrite/java/spring/framework/MigrateMethodArgumentNotValidExceptionErrorMethodTest.java
src/test/java/org/openrewrite/java/spring/framework/MigrateResourceHttpMessageWriterAddHeadersMethodTest.java
src/test/java/org/openrewrite/java/spring/framework/MigrateUriComponentsBuilderMethodsTest.java
src/test/java/org/openrewrite/java/spring/framework/MigrateWebExchangeBindExceptionResolveErrorMethodTest.java

Addresses part of https://github.com/openrewrite/rewrite-spring/issues/627:

Addresses part of Recipes to upgrade to Spring Framework 6.2

---

src/main/java/org/openrewrite/java/spring/boot2/UnnecessarySpringExtension.java
src/testWithSpringBoot_2_3/java/org/openrewrite/java/spring/boot2/SpringBoot2JUnit4to5MigrationTest.java
src/testWithSpringBoot_2_4/java/org/openrewrite/java/spring/boot2/UnnecessarySpringExtensionTest.java

- added new tests and fix recipe behaviour

Removing SpringExtension.class from  ExtendWith annotation

---

src/main/resources/META-INF/rewrite/spring-boot-34.yml
src/main/resources/META-INF/rewrite/spring-cloud-2023.yml
src/main/resources/META-INF/rewrite/spring-cloud-2024.yml

- resolve https://github.com/openrewrite/rewrite-spring/issues/709
Spring 3.4 requires Spring Cloud 2024
This PR achieves that.

Spring Boot 3.4.x requires Spring Cloud 2024.x

---

src/main/java/org/openrewrite/java/spring/batch/MigrateItemWriterWrite.java
src/main/java/org/openrewrite/java/spring/batch/MigrateJobBuilderFactory.java
src/main/java/org/openrewrite/java/spring/batch/MigrateJobParameter.java
src/main/java/org/openrewrite/java/spring/batch/MigrateMethodAnnotatedByBatchAPI.java
src/main/java/org/openrewrite/java/spring/batch/MigrateStepBuilderFactory.java

- Follow up to https://github.com/openrewrite/rewrite-spring/pull/711.
Consistently use Spring Batch 5.1.+ across the Spring Batch recipes.
No
@timtebeek

Explicitly requires Spring Batch 5.1.+

---

src/main/java/org/openrewrite/java/spring/trait/SpringBean.java

remove `Traits` factory method usage.
See https://github.com/openrewrite/rewrite-rewrite/pull/16

Migrate Traits class usage to constructor calls

---

src/main/resources/META-INF/rewrite/flyway-10.yml
src/test/java/org/openrewrite/java/flyway/MigrateToFlyway10Test.java

Flyway 10 migration for Oracle

---

src/main/java/org/openrewrite/java/spring/data/MigrateAuditorAwareToOptional.java
src/test/java/org/openrewrite/java/spring/data/MigrateAuditorAwareToOptionalTest.java

MigrateAuditorAwareToOptional: Don't rewrite AuditorAware returning method invocation

---

src/main/java/org/openrewrite/java/spring/boot3/MaintainTrailingSlashURLMappings.java
src/testWithSpringBoot_2_7/java/org/openrewrite/java/spring/boot2/MaintainTrailingSlashURLMappingsTest.java

Shorten MaintainTrailingSlashURLMappings code by using an inline visitor

---

src/main/resources/META-INF/rewrite/flyway-10.yml
src/test/java/org/openrewrite/java/flyway/MigrateToFlyway10Test.java

Flyway 10 migration for SQL Server (#738)

---

src/main/java/org/openrewrite/java/spring/CommentOutSpringPropertyKey.java
src/main/java/org/openrewrite/java/spring/NoRequestMappingAnnotation.java
src/main/java/org/openrewrite/java/spring/RenameBean.java
src/main/java/org/openrewrite/java/spring/UpdateApiManifest.java
src/main/java/org/openrewrite/java/spring/batch/MigrateJobParameter.java
src/main/java/org/openrewrite/java/spring/batch/MigrateMethodAnnotatedByBatchAPI.java
src/main/java/org/openrewrite/java/spring/boot2/AddConfigurationAnnotationIfBeansPresent.java
src/main/java/org/openrewrite/java/spring/boot2/ConvertToSecurityDslVisitor.java
src/main/java/org/openrewrite/java/spring/boot2/MoveAutoConfigurationToImportsFile.java
src/main/java/org/openrewrite/java/spring/boot2/search/EntityIdForRepositoryVisitor.java
src/main/java/org/openrewrite/java/spring/boot2/search/IntegrationSchedulerPoolRecipe.java
src/main/java/org/openrewrite/java/spring/boot3/AddSetUseTrailingSlashMatch.java
src/main/java/org/openrewrite/java/spring/boot3/MigrateWebMvcTagsToObservationConvention.java
src/main/java/org/openrewrite/java/spring/boot3/RemoveSolrAutoConfigurationExclude.java
src/main/java/org/openrewrite/java/spring/cloud2022/MigrateRequestMappingOnFeignClient.java
src/main/java/org/openrewrite/java/spring/data/MigrateAuditorAwareToOptional.java
src/main/java/org/openrewrite/java/spring/doc/MigrateDocketBeanToGroupedOpenApiBean.java
src/main/java/org/openrewrite/java/spring/framework/MigrateHandlerResultSetExceptionHandlerMethod.java
src/main/java/org/openrewrite/java/spring/framework/MigrateMethodArgumentNotValidExceptionErrorMethod.java
src/main/java/org/openrewrite/java/spring/internal/LocalVariableUtils.java
src/main/java/org/openrewrite/java/spring/security5/AuthorizeHttpRequests.java
src/main/java/org/openrewrite/java/spring/security5/UpdateArgon2PasswordEncoder.java
src/main/java/org/openrewrite/java/spring/security5/UpdatePbkdf2PasswordEncoder.java
src/main/java/org/openrewrite/java/spring/security5/UpdateSCryptPasswordEncoder.java
src/main/java/org/openrewrite/java/spring/security5/WebSecurityConfigurerAdapter.java
src/main/java/org/openrewrite/java/spring/security6/RequireExplicitSavingOfSecurityContextRepository.java
src/main/java/org/openrewrite/java/spring/trait/SpringBean.java

Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.staticanalysis.UnwrapElseAfterReturn?organizationId=ODQ2MGExMTUtNDg0My00N2EwLTgzMGMtNGE1NGExMTBmZDkw

refactor: Unwrap else block after return or throw statement

---

src/main/java/org/openrewrite/java/spring/framework/MigrateResponseStatusExceptionGetRawStatusCodeMethod.java

Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.java.InlineMethodCalls?organizationId=QUxML09wZW4gU291cmNlL09wZW5SZXdyaXRl

Inline methods annotated with `@InlineMe`
