- build.gradle.kts
straightforward fix to no longer need to specify `snapshot`
https://github.com/nebula-plugins/nebula-release-plugin/issues/149
https://youtrack.jetbrains.com/issue/KT-44713
> When you change the order of the plugin so that the Kotlin plugin is applied BEFORE the Nebula plugin, OR you downgrade to Kotlin plugin 1.3.72, then it works as expected.
> 
> This leads me to the conclusion that starting with version 1.4.0 the Kotlin plugin triggers the creation of the version (e.g. by accessing it) when the plugin is applied. This should be reverted to delayed access, e.g. when the plugin's tasks are executed.
> 
> I guess the sequence is like this:
> 
> Gradle applies the plugins
> Nebula release plugin is applied
> Kotlin plugin is applied
> Plugin accesses project.version
> The version is …
> move kotlin jvm plugin before nebula-release [openrewrite/rewrite#324]

- src/main/java/org/openrewrite/java/spring/boot2/ReplaceDeprecatedEnvironmentTestUtils.java
- src/main/resources/META-INF/rewrite/spring-boot2.yml
- src/main/resources/TestPropertyValues.java
- src/test/kotlin/org/openrewrite/java/spring/boot2/ReplaceDeprecatedEnvironmentTestUtilsTest.kt
The class `org.springframework.boot.test.util.EnvironmentTestUtils` is deprecated in Spring Boot 2.x in favor of `TestPropertyValues`. This PR includes a recipe that replaces this. Automatically.
Replace the following:
```
EnvironmentTestUtils.addEnvironment(contextOrEnvironment, keyValuePair1)
EnvironmentTestUtils.addEnvironment(contextOrEnvironment, keyValuePair2)
```
with the following:
```
TestPropertyValues.of(keyValuePair1).and(keyValuePair2).applyTo(contextOrEnvironment);
```
The way it works is as follows:
1. Visit a method declaration
2. If an `addEnvironment` method call is found, start collecting them
3. Coalesce collected `addEnvironment` calls into a single `TestPropertyValues.of/and/applyTo` chain
4. Add a marker to the first collected `addEnvironment` call that includes …
> Replace deprecated EnvironmentTestUtils for Spring Boot 2.x

- src/main/java/org/openrewrite/java/spring/boot2/ReplaceDeprecatedEnvironmentTestUtils.java
- src/test/kotlin/org/openrewrite/java/spring/boot2/ReplaceDeprecatedEnvironmentTestUtilsTest.kt
After additional testing of ReplaceDeprecatedEnvironmentTestUtils, I discovered that the
String parameter at the end was varargs and not being handled correctly. I also
discovered that there was another signature of addEnvironment that wasn't being taken
care of appropriately.
> Add additional method signatures for EnvironmentTestUtils.addEnvironment

- build.gradle.kts
- src/main/java/org/openrewrite/java/spring/boot2/MarkDeprecatedAPIs.java
- src/main/resources/META-INF/rewrite/mark-deprecated-2-minor-version-3-apis.yml
- src/main/resources/META-INF/rewrite/mark-deprecated-2-minor-version-4-apis.yml
- src/main/resources/META-INF/rewrite/mark-deprecated-2-minor-version-5-apis.yml
- src/test/kotlin/org/openrewrite/java/spring/MarkDeprecatedAPIsTest.kt
- src/testWithSpringBoot_2_4/kotlin/org/openrewrite/java/spring/boot2/MarkDeprecated2MinorVersion4APIsTest.kt
Added recipe to mark deprecated APIs in Spring Boot 2.3.
Added recipe to mark deprecated APIs in Spring Boot 2.4.
Added recipe to mark deprecated APIs in Spring Boot 2.5.
> Added recipe to mark deprecated APIs to support framework migration.

- src/main/java/org/openrewrite/java/spring/boot2/search/IntegrationSchedulerPoolRecipe.java
- src/test/kotlin/org/openrewrite/java/spring/boot2/search/IntegrationSchedulerPoolRecipeTest.kt
Fixes #138 
PR for initial feedback because there is usually plenty of feedback ;-)
(cc @fabapp2 )
If conditions are met comment made in `application.properties` file either over the `spring.task.scheduling.pool.size` property or just at the end if property not found. YAML properties still left to add.
> Spring Integration Scheduler Pool Size. Boot -> 2.5

- .gitignore
- src/main/resources/META-INF/rewrite/spring-boot2-upgrade-version.yml
Fixes #181
Not 100% sure if `UpgradeDependencyVersion` also supports a `dependencyManagement` BOM import, but figured worth a try. Otherwise any feedback here should point to what is actually needed.
The goal would be to replace the version number as it appears below from (likely) 2020.0.5 to 2021.0.2, regardless of whether it's managed as a property or directly included.
```
<dependencyManagement>
<dependencies>
<dependency>
<groupId>org.springframework.cloud</groupId>
<artifactId>spring-cloud-dependencies</artifactId>
<version>${spring.cloud-version}</version>
<type>pom</type>
<scope>import</scope>
</dependency>
</dependencies>
</dependencyManagement>
```
> Upgrade spring-cloud-dependencies to 2021.0.2

- src/main/java/org/openrewrite/java/spring/boot3/RemoveConstructorBindingAnnotation.java
- src/testWithSpringBoot_2_4/kotlin/org/openrewrite/java/spring/boot3/RemoveConstructorBindingAnnotationTest.kt
Boot 3 allows for removal of type annotation `@ConstructorBinding` where type has `@ConfigurationProperties`.
See: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M2-Release-Notes#constructingbinding-no-longer-needed-at-the-type-level
cc: @fabapp2
> Boot 3: Remove @ConstructorBinding annotation 

- build.gradle.kts
- src/main/java/org/openrewrite/java/spring/boot2/WebSecurityConfigurerAdapterRecipe.java
- src/testWithSpringBoot_2_4/kotlin/org/openrewrite/java/spring/boot2/WebSecurityConfigurerAdapterRecipeTest.kt
See: https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter
TODO is `configure(AuthenticationManagerBuilder)` - it is left for a later contribution
> Deprecated WebSecurityConfigurerAdapter in spring-security 5.7.1

- src/main/java/org/openrewrite/java/spring/AutowiredFieldIntoConstructorParameterVisitor.java
- src/testWithSpringBoot_2_1/kotlin/org/openrewrite/java/spring/AutowiredFieldIntoConstructorParameterVisitorTest.kt
Takes fq name of the class and field name and converts that field if it is `@Autowired` into constructor parameter if there is a qualifying constructor.
Does need some sort of `getApplicableTest()`? Is it ok to be a  recipe? Or you'd rather have it as a visitor? Feedback is welcomed.
> Autowired field into constructor parameter

- src/main/java/org/openrewrite/java/spring/boot2/SAMLRelyingPartyPropertyApplicationPropertiesMove.java
- src/testWithSpringBoot_2_4/kotlin/org/openrewrite/java/spring/boot2/SAMLRelyingPartyPropertyApplicationPropertiesMoveTest.kt
This PR follow up [PR-205](https://github.com/openrewrite/rewrite-spring/pull/205) which handles yaml property move.
Its similar to PR-205 and handles same logic but for application properties
> Saml rename identity provider app prop

- src/main/java/org/openrewrite/java/spring/boot2/WebSecurityConfigurerAdapter.java
- src/testWithSpringBoot_2_4/kotlin/org/openrewrite/java/spring/boot2/WebSecurityConfigurerAdapterTest.kt
Relax WebSecurityConfigurerAdapter update constraints to allow for transformations when an unrelated method is present. (issue #214)
- If the configuration class should override the `userDetailsServiceBean`, `authenticationManagerBean`, or `configure(AuthenticationManagerBuilder)` then mark them with a comment and exit the transformation.
- Remove`configureHttpSecurityMethodInnerClass` and `configureHttpSecurityMethodInnerClassWithNoApplicableMethod` tests since they appear to be very unlikely configurations.
> R…elax WebSecurityConfigurerAdapter update constraints

- src/main/java/org/openrewrite/java/spring/AutowiredFieldIntoConstructorParameterVisitor.java
- src/testWithSpringBoot_2_1/kotlin/org/openrewrite/java/spring/AutowiredFieldIntoConstructorParameterVisitorTest.kt
@pway99 (cc: @martinlippert)
Code such as
```java
public class A {
@Autowired
private String a;
A() {
this.a = "something";
}
}
```
or 
```java
public class A {
@Autowired
private String a;
A(String a) {
this.a = a;
}
}
```
would still add the field as constructor parameter and add the assignment statement in the constructor. I suggest just short-circuiting and not doing anything in in this case... Not even remove the `@Autowired` in the second snippet...
> Dont convert autowired field if it is initialized in constructor

- src/main/java/org/openrewrite/maven/spring/UpgradeExplicitSpringBootDependencies.java
Update UpgradeExplicitSpringBootDependencies by converting the `springBootDependencyMap` to a field variable of the recipe and only fetch the `org.springframework.boot:spring-boot-dependencies` values once for each recipe instance.
@sambsnyd or @tkvangorder wanted to get your opinion on this one before it runs on the public saas.
cc: @ashakirin
> UpgradeExplicitSpringBootDependencies make `springBootDependencyMap` a field-variable of the recipe

- src/main/resources/META-INF/rewrite/spring-boot-27.yml
- src/main/resources/META-INF/rewrite/spring-boot-30.yml
- src/testWithSpringBoot_3_0/java/org/openrewrite/java/spring/boot3/UpgradeSpringBoot3ConfigurationTest.java
- Display name for 2.6 upgrade inline with other 2.x upgrades
- Commented out extra properties added via actuator endpoint sanitization (We've decided to remove them, correct?)
- Comment out Legacy JMX exposure. Feedback from Boot team indicates they'd rather users to review which endpoints need to be exposed
> Boot 3 upgrade adjustments

- src/main/java/org/openrewrite/java/spring/data/UseTlsJdbcConnectionString.java
- src/test/java/org/openrewrite/java/spring/data/UseTlsJdbcConnectionStringTest.java
This allows for updating JDBC urls which are at different property keys, still within a Spring Boot application context. This particularly becomes useful when an application has more than a single JDBC connection. In these cases, the user often has to use custom properties to create each of their unique JDBC datasource configurations.
> Allow specification of the property key.

- src/main/java/org/openrewrite/java/spring/ChangeSpringPropertyKey.java
- src/test/java/org/openrewrite/java/spring/ChangeSpringPropertyKeyTest.java
- src/testWithSpringBoot_2_4/java/org/openrewrite/java/spring/boot2/UpgradeSpringBoot2ConfigurationTest.java
Current state: if this recipe touches a yaml, then the entire file gets expanded to the indented syntax (no dot separation)
With this PR: yaml props modified by this recipe will always be dot-separated, but the rest of the file remains as it was
Ideally, we'd have some Style logic to attempt to maintain the source file's preferences, but in the interim, this PR should make the recipe more minimally-invasive
> ChangeSpringPropertyKey no longer expands entire affected yaml

- src/main/java/org/openrewrite/java/spring/boot2/WebSecurityConfigurerAdapter.java
- src/testWithSpringBoot_2_4/java/org/openrewrite/java/spring/boot2/WebSecurityConfigurerAdapterTest.java
Fixes #278 
We cannot solve `@Order` annotation port on the bean methods. However, if it is important we can have a white list of annotations that if present over the configuration class can be moved over bean methods of that class.
> Flatten configuration class if possible

- src/main/java/org/openrewrite/java/spring/boot2/ConvertToSecurityDslVisitor.java
- src/main/java/org/openrewrite/java/spring/boot2/HttpSecurityLambdaDsl.java
- src/main/java/org/openrewrite/java/spring/boot2/ServerHttpSecurityLambdaDsl.java
- src/testWithSpringBoot_2_4/java/org/openrewrite/java/spring/boot2/HttpSecurityLambdaDslTest.java
- src/testWithSpringBoot_2_4/java/org/openrewrite/java/spring/boot2/ServerHttpSecurityLambdaDslTest.java
Convert method invocation http on `HttpSecurity` and `ServerHttpSecurity` to the new Lambda DSL syntax. See [Spring Security - Lambda DSL](https://spring.io/blog/2019/11/21/spring-security-lambda-dsl)
> Security DSL

- src/main/java/org/openrewrite/java/spring/boot2/AddConfigurationAnnotationIfBeansPresent.java
- src/testWithSpringBoot_3_0/java/org/openrewrite/java/spring/boot3/AddConfigurationAnnotationIfBeansPresentTest.java
(Kind of a consequence from `@EnableXXXSEcurity` annotations)
If a class has methods annotated with `@Beans` or meta-subclasses of `@Bean` a declaring class likely needs to have `@Configuration` or some meta-subclass annotation. If it is missing the recipe would add `@Configuration`.
Useful if someone upgraded to Boot 3 and Security 6 manually without adding missing `@Configuration` next to `@EnableXXXSecurity` then this recipe would be useful.
I think it'll be useful in the IDE world mostly for those who forgot `@Configuration` in a class defining beans.
> Add @Configuration over a class having @Bean methods

- src/main/java/org/openrewrite/java/spring/boot2/ReplaceExtendWithAndContextConfiguration.java
- src/main/java/org/openrewrite/java/spring/boot2/UnnecessarySpringExtension.java
- src/main/resources/META-INF/rewrite/spring-boot-24.yml
- src/testWithSpringBoot_2_3/java/org/openrewrite/java/spring/boot2/SpringBoot2JUnit4to5MigrationTest.java
- src/testWithSpringBoot_2_4/java/org/openrewrite/java/spring/boot2/ReplaceExtendWithAndContextConfigurationTest.java
This recipe will convert JUnit 5 test classes that use both `@ExtendWith` and `@ContextConfiguration` into [`@SpringJUnitConfig`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/test/context/junit/jupiter/SpringJUnitConfig.html).
It changes the `@ContextConfiguration` annotation into `@SpringJUnitConfig`, with a few modifications:
- The `loader()` attribute on `@ContextConfiguration` is not supported on `@SpringJUnitConfig`, so if this is encountered, the transformation is abandoned out of caution and to adhere to the "do no harm" principle.
- The `value()` attribute on `@ContextConfiguration` needs to be renamed to `locations()`. It's invalid for an existing `@ContextConfiguration` annotation to be using both `value()` and `locations()`, but if this …
> Add recipe to consolidate @ExtendWith and @ContextConfiguration

- src/main/resources/META-INF/rewrite/spring-boot-24.yml
- src/testWithSpringBoot_2_3/java/org/openrewrite/java/spring/boot2/SpringBoot2JUnit4to5MigrationTest.java
This PR enables the recipe to convert JUnit 5 test classes that use both `@ExtendWith` and `@ContextConfiguration` into [`@SpringJUnitConfig`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/test/context/junit/jupiter/SpringJUnitConfig.html) in the [JUnit 4 to JUnit 5 migration recipe](https://docs.openrewrite.org/reference/recipes/java/spring/boot2/springboot2junit4to5migration).
Closes #296 
See #297
> Enable recipe in JUnit 5 migration (#296)

- src/main/resources/META-INF/rewrite/spring-boot-30.yml
Remove Saml2 property migration from boot 3.0 migration as it is meant for Boot 2.7 migration only
> Saml2 property changes only for 2.7

- src/main/resources/META-INF/rewrite/spring-boot-20.yml
I don't think we can justify this as a standard best practice (which gets run in every Spring Boot upgrade recipe past 2.x), and it's a pretty noisy change for projects which don't already use this style.
The closest mention I see in Spring Boot reference docs is this:
https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-factorybeans-annotations
> The Java language visibility of @Bean methods does not have an immediate impact on the resulting bean definition in Spring’s container. You can freely declare your factory methods as you see fit in non-@Configuration classes and also for static methods anywhere. However, regular @Bean methods in @Configuration classes need to be overridable — that is, they must not be declared as private or final.
...and all the …
> Removed BeanMethodsNotPublic from SpringBoot2BestPractices

- src/main/java/org/openrewrite/java/spring/boot3/AddSetUseTrailingSlashMatch.java
- src/main/java/org/openrewrite/java/spring/boot3/MaintainTrailingSlashURLMappings.java
- src/testWithSpringBoot_2_7/java/org/openrewrite/java/spring/boot2/AddSetUseTrailingSlashMatchTest.java
- src/testWithSpringBoot_2_7/java/org/openrewrite/java/spring/boot2/MaintainTrailingSlashURLMappingsTest.java
Add recipe `AddSetUseTrailingSlashMatch` to add `configurer.setUseTrailingSlashMatch(true);` method invocation to `WebMvcConfigurer` class or `WebFluxConfigurer` to change the default with the global Spring MVC or Webflux configuration.
This is part of SB 3.0 task [Maintain trailing slash in request mappings](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#spring-mvc-and-webflux-url-matching-changes) , after this recipe, this task is completed.
> [SB 3.0 recipe] Add recipe AddSetUseTrailingSlashMatch

- src/main/java/org/openrewrite/java/spring/boot3/ConfigurationOverEnableSecurity.java
- src/testWithSpringBoot_2_7/java/org/openrewrite/java/spring/boot2/ConfigurationOverEnableSecurityTest.java
Change `ConfigurationOverEnableSecurity` to modify only before Boot3. 
and no change if it's already Boot 3.
Slack discussion [here](https://moderneinc.slack.com/archives/C017J8U6ZGC/p1679331496438579).
> Change `ConfigurationOverEnableSecurity` to modify only before Boot3

- build.gradle.kts
- src/main/java/org/openrewrite/java/spring/security6/UpdateRequestCache.java
- src/testWithSpringSecurity_5_8/java/org/openrewrite/spring/security5/UpdateRequestCacheTest.java
This recipe is part of  [Spring Security 6.0 migration ](https://github.com/openrewrite/rewrite-spring/issues/256) to [Optimize Querying of RequestCache](https://docs.spring.io/spring-security/reference/6.0.0/migration/servlet/session-management.html#requestcache-query-optimization)
By default, Spring Security 5 queries the saved request on every request, which means that in a typical setup, the HttpSession is queried on every request to use the RequestCache. In Spring Security 6, the default behavior has changed, and RequestCache will only be queried for a cached request if the HTTP parameter `continue` is defined. This helps Spring Security avoid unnecessary HttpSession queries with the RequestCache. To maintain the same default behavior as Spring Security 5, either explicitly add the …
> [Spring Security6 migration] Add recipe UpdateRequestCacheTest

- src/main/java/org/openrewrite/java/spring/security6/RemoveOauth2LoginConfig.java
- src/testWithSpringSecurity_5_8/java/org/openrewrite/spring/security5/RemoveOauth2LoginConfigTest.java
This recipe is part of the [Spring Security6 migration](https://github.com/openrewrite/rewrite-spring/issues/256) to implement to keep [Default authorities for oauth2Login()](https://docs.spring.io/spring-security/reference/6.0.0/migration/servlet/authentication.html#_default_authorities_for_oauth2login).
> [Spring Security6 migration]Add recipe `RemoveOauth2LoginConfig`

- src/main/java/org/openrewrite/java/spring/security6/RequireExplicitSavingOfSecurityContextRepository.java
- src/main/java/org/openrewrite/java/spring/security6/UpdateEnableReactiveMethodSecurity.java
- src/main/resources/META-INF/rewrite/spring-security-60.yml
- src/testWithSpringSecurity_5_8/java/org/openrewrite/spring/security5/UpdateEnableReactiveMethodSecurityTest.java
This recipe is part of the [Spring Security 6.0 migration ](https://github.com/openrewrite/rewrite-spring/issues/256).
In Spring Security 6.0, `@EnableReactiveMethodSecurity` defaults `useAuthorizationManager` to true. So, to complete migration, `@EnableReactiveMethodSecurity` remove the `useAuthorizationManager` attribute. 
Reference : [here](https://docs.spring.io/spring-security/reference/6.0.0/migration/reactive.html)
Before
```java
@EnableReactiveMethodSecurity(useAuthorizationManager = true)
```
After
```java
@EnableReactiveMethodSecurity
```
> [Spring security 6 migration] Adds `UpdateEnableReactiveMethodSecurity` recipe

- src/main/java/org/openrewrite/java/spring/ImplicitWebAnnotationNames.java
- src/testWithSpringBoot_2_1/java/org/openrewrite/java/spring/ImplicitWebAnnotationNamesTest.java
Auto-format variable declaration when an argument is removed. Fixes #340
> ImplicitWebAnnotationNames - auto-format variable declaration when an argument is removed.

- src/main/java/org/openrewrite/java/spring/security5/WebSecurityConfigurerAdapter.java
- src/main/resources/META-INF/rewrite/spring-boot-27.yml
- src/main/resources/META-INF/rewrite/spring-security-58.yml
- src/testWithSpringSecurity_5_7/java/org/openrewrite/spring/security5/WebSecurityConfigurerAdapterTest.java
Move `WebSecurityConfigurerAdapter` recipe from `boot2` to `security5`.
And add it to the security5.8 migration recipe list.
As it's part of security5.8 migration ([doc](https://docs.spring.io/spring-security/reference/5.8/migration/servlet/config.html#_publish_a_securityfilterchain_bean)), so should be in `security5`.
> move `WebSecurityConfigurerAdapter` recipe to security5

- src/main/resources/META-INF/rewrite/spring-boot-20.yml
Switch `org.openrewrite.java.dependencies.UpgradeParentVersion` back to `org.openrewrite.maven.UpgradeParentVersion`
Fixes #371
Introduced in https://github.com/openrewrite/rewrite-spring/commit/5e90a83ebedf970800cdb4719f46852bb132a40d , likely as an oversight there, as there is [no equivalent UpgradeParentVersion in rewrite-java-dependencies](https://github.com/openrewrite/rewrite-java-dependencies/tree/main/src/main/java/org/openrewrite/java/dependencies). The Gradle UpgradeDependencyVersion [handles platform dependencies as well](https://github.com/openrewrite/rewrite/blob/fdced008df89f861e33e73e39457db154adcc4a0/rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeDependencyVersionTest.java#L233-L246), which is already covered in the recipe just above the one changed here..
> Upgrade Maven parent only; Gradle should work with BOM already

- build.gradle.kts
- src/main/resources/META-INF/rewrite/spring-boot-27.yml
- src/testWithSpringBoot_2_7/java/org/openrewrite/java/spring/boot2/UpdateMysqlDriverArtifactIdTest.java
Adapted the maven specific mysql dependency update to the generic one to include gradle
Fixes #375
> Adapted the maven specific mysql dependency update to the generic one to include gradle

- src/main/resources/META-INF/rewrite/spring-boot-30.yml
Change package when upgrading Thymeleaf from spring 5 to spring 6.
We already change the dependency; the package should then also change, as [reported via Slack](https://rewriteoss.slack.com/archives/C01A843MWG5/p1688048543125899?thread_ts=1688048009.901689&cid=C01A843MWG5).
> Change package org.thymeleaf.spring 5 to spring6

- src/main/java/org/openrewrite/java/spring/amqp/UseTlsAmqpConnectionString.java
- src/test/java/org/openrewrite/java/spring/amqp/UseTlsAmqpConnectionStringTest.java
src/main/java/org/openrewrite/java/spring/amqp/UseTlsAmqpConnectionString.java recipe will now use default values for `propertyKey` and `tlsPropertyKey` when these options are supplied as empty strings. 
The recipe does not default options when an empty string is supplied and an empty string is not a valid key. 
@shanman190 
For the Moderne SaaS the alternative is to not default strings to "" which may happen from this PR: https://github.com/openrewrite/rewrite/pull/3404/files.
> fix: use default values for propertyKey and tlsPropertyKey when empty string.

- src/main/resources/META-INF/rewrite/spring-boot-20.yml
- src/main/resources/META-INF/rewrite/spring-boot-21.yml
- src/main/resources/META-INF/rewrite/spring-boot-22.yml
- src/main/resources/META-INF/rewrite/spring-boot-23.yml
- src/main/resources/META-INF/rewrite/spring-boot-25.yml
- src/main/resources/META-INF/rewrite/spring-boot-30.yml
- src/testWithSpringBoot_2_7/java/org/openrewrite/gradle/spring/UpdateGradleTest.java
Re-enabled all UpdateGradle recipes on SpringBoot migration recipes and re-enabled and fixed the tests
We can run this recipe in a reliable way in the SaaS again, so it makes sense to add again the recipe to the SpringBoot migration recipes.
> re-enabled the UpdateGradle recipes

- src/main/java/org/openrewrite/java/spring/NoRequestMappingAnnotation.java
- src/testWithSpringBoot_2_1/java/org/openrewrite/java/spring/NoRequestMappingAnnotationTest.java
Only apply NoRequestMappingAnnotation if there's a `method` argument with a target mapping annotation replacement.
`@RequestMapping` without `method` matches all methods, so it's not safe to convert.
We could add a comment to the `@RequestMapping("/foo")` annotations that these require work, but that produce a lot of such messages.
Previously we matched all, or even missing methods; that's a bug.
> Ony selectively apply NoRequestMappingAnnotation

- src/main/java/org/openrewrite/java/spring/security5/UseNewRequestMatchers.java
- src/testWithSpringSecurity_5_7/java/org/openrewrite/spring/security5/UseNewSecurityMatchersTest.java
- src/testWithSpringSecurity_5_8/java/org/openrewrite/spring/security5/UseNewRequestMatchersTest.java
Adopt JavaTemplate to replace methods.
Replacements failed as we looked for a replacement method in the target type, but only 5.7 classes were available, leading to a mismatch and thus no replacement. Fixes #350
Called out below.
> UseNewRequestMatchers should also replace with 5.7 on classpath

- build.gradle.kts
- src/main/resources/META-INF/rewrite/apache-httpclient-5.yml
- src/test/java/org/openrewrite/java/apache/httpclient5/NamespaceChangesTest.java
- src/test/java/org/openrewrite/java/apache/httpclient5/UpgradeApacheHttpClient5Test.java
Added a first approach of Apache Http Client 5 migration. Right now it adds the new dependency coordinates and performs all the obvious mappings between compatible classes changing the namespace.
Some attempts on some Deprecated classes have been done, but probably with some breaking changes right now. Will need more iteration.
Spring boot 3 migration requires HttpClient upgrade.
Issue: #300 
@timtebeek
> first approach of HttpClient5 migration

- src/main/java/org/openrewrite/java/apache/httpclient5/NewStatusLine.java
- src/main/resources/META-INF/rewrite/apache-httpclient-5.yml
- src/test/java/org/openrewrite/java/apache/httpclient5/UpgradeApacheHttpClient5Test.java
HttpResponse::getStatusLine has been removed in Apache HttpClient 5.x, you can call the getStatusCode, getProtocolVersion and getReasonPhrase directly on the HttpResponse object.
When applicable, we will apply a simplify method chain, but for scenarios where the StatusLine is stored or used directly, we are going to instantiate a StatusLine object (which has the same previous 4.x methods) with the response object.
> Replace getStatusLine on HttpResponse

- build.gradle.kts
- src/main/java/org/openrewrite/java/spring/boot2/ConvertToSecurityDslVisitor.java
- src/main/java/org/openrewrite/java/spring/boot2/HttpSecurityLambdaDsl.java
- src/main/java/org/openrewrite/java/spring/boot2/ServerHttpSecurityLambdaDsl.java
- src/testWithSpringBoot_2_1/java/org/openrewrite/java/spring/boot2/LegacyHttpSecurityTest.java
Also added/fixed the precondition setup such that the recipe now only runs over `JavaSourceFile` instances that use the specific `HttpSecurity` type.
> `HttpSecurityLambdaDsl` and `ServerHttpSecurityLambdaDsl` are overly eager when running against very old Spring Security versions

- src/main/java/org/openrewrite/java/spring/ImplicitWebAnnotationNames.java
- src/testWithSpringBoot_2_1/java/org/openrewrite/java/spring/ImplicitWebAnnotationNamesTest.java
Removed unnecessary autoFormat
This recipe, in combination with others that called autoFormat on annotations, could cause autoFormat to cause unexpected results because it was finding a message in a cursor that was causing to change indentation.
Any corner case where the autoFormat was needed?
@timtebeek
> removed unnecessary autoFormat

- src/main/java/org/openrewrite/java/spring/ImplicitWebAnnotationNames.java
Manually formatting potential introduced errors due to removal of annotation arguments
Calling autoFormat has some unwanted side effects, probably due to some bugs in autoFormat. However, we do not actually need to call autoFormat here, since the span of potential format changes needed is small and we can take care of it in the recipe itself.
@timtebeek
> removed autoFormat and replaced with manual format

- src/main/resources/META-INF/rewrite/apache-httpclient-5.yml
Let the `UpgradeApacheHttpClient_5` recipe upgrade the `org.apache.httpcomponents:httpcore` dependency to `org.apache.httpcomponents.core5:httpcore5`. 
When running the `UpgradeApacheHttpClient_5` we had to perform this part of the upgrade manually. With this addition, not anymore 😉. 
@timtebeek
> Upgrade `httpcore` -> `httpcore5` in the `UpgradeApacheHttpClient_5` recipe

- src/main/java/org/openrewrite/java/spring/batch/RemoveDefaultBatchConfigurer.java
- src/main/resources/META-INF/rewrite/spring-batch-5.0.yml
- src/testWithSpringBoot_3_0/java/org/openrewrite/java/spring/batch/RemoveDefaultBatchConfigurerTest.java
Added a `RemoveDefaultBatchConfigurer` recipe to help migrate Spring Batch.
Fixes #412
Any additional cases we should cover?
Should we handle the disabled `retainInterfaceOverrides` test case?
- https://github.com/openrewrite/rewrite-spring/issues/412
> Remove DefaultBatchConfigurer

- build.gradle.kts
- src/main/resources/META-INF/rewrite/spring-boot-30.yml
- src/main/resources/META-INF/rewrite/spring-boot-31.yml
- Added dependency on rewrite-hibernate
- Chain in Hibernate 6.1/62 migrations when upgrading Spring Boot 3.0/3.1
> I'd like to have this recipe while running Boot 2.x to 3.x upgrade. -- @BoykoAlex 
We _could_ migrate hibernate as part of Spring Framework migrations instead, but this seemed most appropriate given the managed dependency versions.
- https://github.com/openrewrite/rewrite-hibernate/pull/8
- https://docs.spring.io/spring-boot/docs/3.0.x/reference/htmlsingle/#appendix.dependency-versions.coordinates
- https://docs.spring.io/spring-boot/docs/3.1.x/reference/htmlsingle/#appendix.dependency-versions
> Migrate Hibernate as part of Spring Boot migration

- src/main/java/org/openrewrite/java/spring/boot2/ConvertToSecurityDslVisitor.java
- src/main/java/org/openrewrite/java/spring/boot2/HeadersConfigurerLambdaDsl.java
- src/main/resources/META-INF/rewrite/spring-boot-24.yml
- src/main/resources/META-INF/rewrite/spring-boot-31.yml
- src/main/resources/META-INF/rewrite/spring-security-61.yml
- src/testWithSpringBoot_2_4/java/org/openrewrite/java/spring/boot2/HeadersConfigurerLambdaDslTest.java
Two things:
- moved Spring Security Lambda DSL recipes from SB 2.4 to the point at which the non-lambda DSL was deprecated: Spring Security 6.1 (new file) used by SB 3.1
- added argReplacements option to ConvertToSecurityDslVisitor, enabling migration of non-lambda-DSL overloads which accept an argument. then used that new feature to implement HeadersConfigurerLambdaDsl.
- avoiding making changes "too early"
- #415
The changes to `ConvertToSecurityDslVisitor` haven't broken any existing tests, but, still good to spot-check.
Also, if anyone is aware of other HttpSecurity-relevant methods which can be covered now that we have the `argReplacements` mechanism, then it would be good to (minimally) define that scope.
@shanman190 @BoykoAlex @timtebeek 
- ~~[ ] I've updated the documentation (if …
> Security lambda DSL enhancements

- src/main/java/org/openrewrite/java/spring/http/SimplifyMediaTypeParseCalls.java
- src/test/java/org/openrewrite/java/spring/SimplifyMediaTypeParseCallsTest.java
This PR introduces a recipe to replaces uses of `MediaType.parse("application/json")` with `MediaType.APPLICATION_JSON`. 
Fixes https://github.com/openrewrite/rewrite-spring/issues/337
Currently when the recipe runs the `methodType` for `MediaType.parse` is null which is causing the recipe to stop running early. I think it is because I am not including the correct classpath. I have tried using `classpath("spring-web")` but it kept telling me that this was not a valid resource name. I'm confused why it would tell me that since I've seen `spring-web` used in other tests in rewrite-spring.
@timtebeek
> Simplify `MediaType.parse` Calls

- src/main/java/org/openrewrite/java/spring/batch/MigrateItemWriterWrite.java
- src/testWithSpringBoot_3_0/java/org/openrewrite/java/spring/batch/MigrateItemWriterWriteTest.java
After changing the type of the method, we can have scenarios where the method was manipulating the original List, and the used methods does not exist in Chunk. So we need to call `Chunk::getItems` to retrieve the actual list and keep compilable code.
Also calling getItems when needed on assignments, variable initialization and method invocations (if the destination type is not `java.lang.Iterable` since it's the only common interface between List and Chunk).
Fixes #411 
Any other corner case where we should call getItems?
@timtebeek @sambsnyd
> Update usage of list and call getItems when needed

- src/main/java/org/openrewrite/java/spring/security5/AuthorizeHttpRequests.java
- src/main/resources/META-INF/rewrite/spring-security-58.yml
- src/testWithSpringBoot_2_7/java/org/openrewrite/java/spring/security5/AuthorizeHttpRequestsTest.java
- Moved into `security5` package, as both methods are available in 5.8
- Wrap `doAfterVisit` calls inside a method, instead of always executing those
- Linked the recipe into the 5.8 spring security upgrade
- Formatting changes
Got reports of these changes not being applied, despite a recipe being available.
- Was there any particular reason this recipe was not hooked into the yaml chain of recipes?
- Was there a reason to keep this under `boot2` instead of `security5`?
@BoykoAlex
> Chain in AuthorizeHttpRequests with spring-security-58.yml

- src/main/java/org/openrewrite/java/spring/security6/oauth2/client/OAuth2ClientLambdaDsl.java
- src/main/java/org/openrewrite/java/spring/security6/oauth2/client/OAuth2LoginLambdaDsl.java
- src/main/java/org/openrewrite/java/spring/security6/oauth2/server/resource/OAuth2ResourceServerLambdaDsl.java
- src/main/resources/META-INF/rewrite/spring-security-60.yml
- src/main/resources/META-INF/rewrite/spring-security-61.yml
- src/testWithSpringBoot_2_4/java/org/openrewrite/java/spring/security6/oauth2/client/OAuth2ClientLambdaDslTest.java
- src/testWithSpringBoot_2_4/java/org/openrewrite/java/spring/security6/oauth2/client/OAuth2LoginLambdaDslTest.java
- src/testWithSpringBoot_2_4/java/org/openrewrite/java/spring/security6/oauth2/server/resource/OAuth2ResourceServerLambdaDslTest.java
Add lambda dsl conversions for `oauth2Login`, `oauth2Client`, and `oauth2ResourceServer` subcomponents.
Preparing for the Spring Security 7.x migration where the lambda DSL will be required.
@timtebeek @nmck257 @BoykoAlex
> Convert `oauth2*` Spring Security subcomponents to lambda dsl

- src/testWithSpringBoot_2_7/java/org/openrewrite/gradle/spring/UpdateGradleTest.java
- src/testWithSpringBoot_2_7/java/org/openrewrite/java/spring/boot2/UpdateMysqlDriverArtifactIdTest.java
There has been a new patch release of 2.7.x
Updated the tests so we validate that the updated version is in the 2.7.x range instead of looking for an specific match.
> bump some versions on some tests

- src/main/java/org/openrewrite/maven/spring/UpgradeExplicitSpringBootDependencies.java
Moved some code to inner MavenVisitor and passing the settings and profiles to the MavenPomDownloader class
Without proper usage of maven settings, some people might find out that their configured repositories are ignored.
> fixed usage of PomDownloader without settings

- src/main/resources/META-INF/rewrite/spring-boot-30.yml
Closes #430
Add a recipe to upgrade to springdoc-openapi 2 as part of the spring boot 3 upgrade
https://github.com/openrewrite/rewrite-spring/issues/430
> Add recipe to upgrade to springdoc-openapi 2

- src/main/resources/META-INF/rewrite/spring-boot-25.yml
- src/main/resources/META-INF/rewrite/spring-boot-26.yml
- src/testWithSpringBoot_2_5/java/org/openrewrite/java/spring/boot2/UpdateMysqlDriverArtifactIdTest.java
[Spring Boot 2.5.15](https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.5.15/spring-boot-dependencies-2.5.15.pom) mismanages a [pom-only redirect pom of mysql:mysql-connector-java:8.0.33](https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.33/)
From 2.6 onwards the managed dependency is com.mysql:mysql-connector-j:8.0.33
Broken migration.
> Fix mysql dependency in 2.5 already

- src/main/resources/META-INF/rewrite/spring-boot-32.yml
- src/main/resources/META-INF/rewrite/spring-cloud-2022.yml
- src/main/resources/META-INF/rewrite/spring-cloud-2023.yml
For Spring Boot 3.2 upgrade.
- https://spring.io/blog/2023/11/02/spring-cloud-2023-0-0-rc1-aka-leyton-is-now-available
- https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2023.0-Release-Notes
- https://twitter.com/m_halbritter/status/1728052671469216167
> Upgrade to Spring Cloud 2023 as part of Spring Boot 3.2

- build.gradle.kts
- src/main/java/org/openrewrite/java/spring/boot2/ConvertToSecurityDslVisitor.java
- src/main/java/org/openrewrite/java/spring/security6/ApplyToWithLambdaDsl.java
- src/main/resources/META-INF/rewrite/spring-security-62.yml
- src/testWithSpringSecurity_6_2/java/org/openrewrite/spring/security6/.editorconfig
- src/testWithSpringSecurity_6_2/java/org/openrewrite/spring/security6/ApplyToWithLambdaDslTest.java
Fixes #449
- Added another SourceSet for Spring Security 6.2
- The overloaded constructor options on `ConvertToSecurityDsl` are starting to feel a little clunky, but I think that with the addition of this recipe we've pretty much covered the full scope of the Lambda DSL migration, so I don't anticipate we'd need to extend this visitor much further
- (not directly related to the PR) I wonder if we could create some generic / fluent API for slicing and dicing a method invocation chain... I feel like I've seen that problem solved several times in individual recipes/visitors, and it tends to be non-trivial, but with the right abstraction, it might be reusable?...
Others who've been in this file a bunch: @shanman190 @BoykoAlex
> HttpSecurity - replace `apply` with `with`

- src/main/java/org/openrewrite/maven/spring/UpgradeExplicitSpringBootDependencies.java
Updated link used for Spring snapshot repo from [https://repo.spring.io/snapshote](https://repo.spring.io/snapshote) (invalid link) to [https://repo.spring.io/snapshot](https://repo.spring.io/snapshot).
Obvious typo
> Fix typo in Spring snapshot repo url

- src/main/resources/META-INF/rewrite/spring-boot-24.yml
- src/testWithSpringBoot_2_3/java/org/openrewrite/java/spring/boot2/SpringBoot2JUnit4to5MigrationTest.java
As that includes `TestsShouldNotBePublic`, which is an opinionated recipe that results in a lot of (optional) changes.
As reported via Slack: https://rewriteoss.slack.com/archives/C01A843MWG5/p1705404676460549
> Remove `JUnit5BestPractices` from `RemoveObsoleteRunners`

- build.gradle.kts
- src/main/java/org/openrewrite/java/apache/httpclient5/AddTimeUnitArgument.java
- src/main/java/org/openrewrite/java/apache/httpclient5/NewStatusLine.java
- src/test/java/org/openrewrite/java/apache/httpclient5/CookieConstantsTest.java
- src/testWithSpringBoot_1_5/java/org/openrewrite/java/spring/NoAutowiredOnConstructorTest.java
As reported via Discord on https://github.com/apache/olingo-odata4
```
[ERROR] Failed to execute goal org.openrewrite.maven:rewrite-maven-plugin:5.21.0:run (default-cli) on project odata-server-sample: Execution default-cli of goal org.openrewrite.maven:rewrite-maven-plugin:5.21.0:run failed: Error while visiting lib/client-core/src/main/java/org/apache/olingo/client/core/communication/request/AsyncRequestWrapperImpl.java: java.lang.IllegalStateException: Unable to construct Java17Parser.
[ERROR]   org.openrewrite.java.Java17Parser$Builder.build(Java17Parser.java:96)
[ERROR]   org.openrewrite.java.Java17Parser$Builder.build(Java17Parser.java:63)
[ERROR]   org.openrewrite.java.internal.template.JavaTemplateParser.compileTemplate(JavaTemplateParser.java:244)
[ERROR] …
```
> Apache HttpClient5 recipes should load classpath from resources

- .github/workflows/properties.yml
- build.gradle.kts
- src/test/java/org/openrewrite/java/spring/internal/GeneratePropertiesMigratorConfiguration.java
Added a workflow that calls `GeneratePropertiesMigratorConfiguration` every week and creates a pull request if there are changes.
Create new recipes when new versions of Spring come out automatically, such that it's not forgotten.
> Periodically generate Spring Boot property migration recipes

- src/main/java/org/openrewrite/java/spring/ChangeSpringPropertyKey.java
- src/main/java/org/openrewrite/java/spring/ChangeSpringPropertyValue.java
- src/main/java/org/openrewrite/java/spring/RenameBean.java
As seen in automated review on
- https://github.com/openrewrite/rewrite-spring/pull/470
> Add missing example values

- build.gradle.kts
- src/main/resources/META-INF/rewrite/springdoc.yml
- src/test/java/org/openrewrite/java/springdoc/SwaggerToSpringDocTest.java
- src/test/java/org/openrewrite/java/springdoc/UpgradeOpenAPI3Test.java
Added recipe to migrate from Swagger to SpringDoc, and upgrade SpringDoc itself.
Required for a complete migration to Spring Boot 3, which was not covered up to now.
Informally shared and tested; now adopted here to help folks that still need to migrate.
- https://github.com/openrewrite/rewrite-openapi/issue/1
- https://github.com/openrewrite/rewrite-openapi/pull/2
> Migrate Swagger to SpringDoc

- src/main/java/org/openrewrite/java/apache/httpclient4/MigrateDefaultHttpClient.java
Signed-off-by: Jonathan Leitschuh <Jonathan.Leitschuh@gmail.com>
Adds documentation to `MigrateDefaultHttpClient`.
Add further indications that this recipie also addresses a security issue.
> Improve `MigrateDefaultHttpClient` documentation

- build.gradle.kts
- src/main/java/org/openrewrite/java/spring/boot3/DowngradeServletApiWhenUsingJetty.java
- src/testWithSpringBoot_2_5/java/org/openrewrite/java/spring/boot2/UpdateMysqlDriverArtifactIdTest.java
- src/testWithSpringBoot_2_7/java/org/openrewrite/gradle/spring/UpdateGradleTest.java
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.java.ChangeMethodTargetToStatic?organizationId=T3BlblJld3JpdGU%3D
> `org.openrewrite.gradle.Assertions#withToolingModel` moved to `org.openrewrite.gradle.toolingapi.Assertions`

- src/main/java/org/openrewrite/java/spring/PropertiesToKebabCase.java
Following https://github.com/openrewrite/rewrite/commit/3ad716352c9bc5a12417aa4d5c36b3f3aff322f9 Reverts https://github.com/openrewrite/rewrite-spring/commit/fa4e1c9c20d7373ea1d5d3bf1fdf44a29ab6c537
> Restore curly brace in PathUtils#matchesGlob

- src/main/resources/META-INF/rewrite/spring-boot-30.yml
- src/testWithSpringBoot_3_0/java/org/openrewrite/java/spring/boot3/MigrateDropWizardDependenciesTest.java
Added Recipe for migrating dropwizard dependencies to spring boot 3.x
I would love explore and contribute more on open-source and for openrewrite framework
@timtebeek  Could you please review it. Thanks.
> Added Recipe for Migrating Dropwizard Dependencies

- src/main/resources/META-INF/rewrite/spring-boot-30.yml
- src/main/resources/META-INF/rewrite/spring-framework-60.yml
- src/test/java/org/openrewrite/java/spring/framework/MigrateSpringAssertTest.java
Added a base recipe for migrating to Spring Framework 6.
This is not a complete migration, but can serve as a place to put Spring-related migrations necessary (as opposed to changes related to only Spring Boot).
https://github.com/openrewrite/rewrite-spring/issues/521
I copied the format from the earlier `UpgradeSpringFramework_5_3`.
I have tested the changes under `MigrateSpringAssert` in our internal migration and it seems to work fine.
I have taken the literal text added from the Spring class and reformatted them a bit.
Ideally, the message contain variable name but that would be a harder change to write automatically.
Usage of this is probably not too common anyway as the functions have been deprecated for a long time.
> Spring Framework 6.0 recipe with migration for Spring `Assert`

- src/main/resources/META-INF/rewrite/spring-boot-32.yml
- https://github.com/spring-projects/spring-boot/issues/37667
- https://github.com/spring-projects/spring-boot/commit/c22548982abf0b9c5c02406fe789b0423fcfa02d
References to these classes could occur anywhere, but in particular in Dockerfiles & manifest files.
References from Java files should be rare; as such I didn't feel a need to add a precondition to limit where we match and replace.
We could still add a precondition if this proves troublesome, for instance when it affects pom.xml files that might refer to these classes.
> Relocate Launcher classes renamed in Spring Boot 3.2

- src/main/resources/META-INF/rewrite/spring-boot-20.yml
- src/testWithSpringBoot_2_7/java/org/openrewrite/java/spring/boot2/Boot3UpgradeTest.java
Fixes #542
Used `preconditions` if **spring-core** is 4.x then we can upgrade to boot 2.x
> Attempt not to run boot upgrade 1.x -> 2.x for projects on 2.x already

- src/main/java/org/openrewrite/java/spring/boot2/MigrateLocalServerPortAnnotation.java
- src/testWithSpringBoot_1_5/java/org/openrewrite/java/spring/boot2/MigrateLocalServerPortAnnotationTest.java
Removes classifier setting on dependency added when migrating LocalServerPort
Fixes https://github.com/openrewrite/rewrite-spring/issues/541
> Remove classifier on dependency added migrating LocalServerPort

- src/main/java/org/openrewrite/java/spring/boot2/MoveAutoConfigurationToImportsFile.java
- src/testWithSpringBoot_2_7/java/org/openrewrite/java/spring/boot2/MoveAutoConfigurationToImportsFileTest.java
* Previously, there was a bug where a second `@AutoConfiguration` was added to the class, even though an existing one was present. This has been fixed
* A new optional parameter to preserve old `spring.factories` file was added, defaults to false. This is for instances where backward compatibility is desired.
* fix bug where the nested `@Configuration` classes get their annotation removed.
closes #548
> feat: `MoveAutoConfigurationToImportsFile` improvements 

- build.gradle.kts
- src/main/resources/META-INF/rewrite/spring-boot-33.yml
Partially resolves #526
* Add Micrometer 1.13.x upgrade to Spring Boot 3.3.x migration: https://github.com/openrewrite/rewrite-micrometer/pull/11
* Spring Boot 3.3.x includes Micrometer 1.13.x which introduced [breaking changes](https://github.com/micrometer-metrics/micrometer/wiki/1.13-Migration-Guide)
* [As Tim suggested](https://github.com/openrewrite/rewrite-micrometer/pull/11#issuecomment-2225187584) I specifically included the migration to verison 1.13.x in the recipe list as opposed to the generic micrometer upgrade recipe to avoid "surprises" with regards to versions in the future
@timtebeek
> Add Micrometer 1.13.x upgrade to Spring Boot 3.3.x migration

- build.gradle.kts
- src/main/resources/META-INF/rewrite/spring-boot-20.yml
- src/testWithSpringBoot_1_5/java/org/openrewrite/java/spring/boot2/Boot2UpgradeTest.java
- src/testWithSpringBoot_2_2/java/org/openrewrite/java/spring/boot2/Boot2UpgradeTest.java
narrowing the precondition on the SB 2.0 recipe to ensure it runs more consistently.
https://github.com/openrewrite/rewrite-spring/pull/543/files#r1678212731
the new precondition is better, but does have a false positive if running the 2.2 recipe on a 2.2 project and a false negative if running the 2.7 recipe on a 2.7 project. this is hard to avoid. the javax.validation-api dep is necessary for SB 2.3 (when hibernate-validator 6.1 swaps its transitive dep from javax to jakarta) through SB 2.7 until SB 3.0 (when spring swaps to jakarta). and with this recipe's placement, it has to make an educated guess about the "final" version of SB for the project after all other recipes in the chain complete while only knowing the current version.
@BoykoAlex 
a nice counterbalance to this recipe might …
> Spring Boot 2.0 - moving the precondition to run in more cases

- src/main/java/org/openrewrite/java/spring/batch/MigrateItemWriterWrite.java
- src/main/java/org/openrewrite/java/spring/batch/ReplaceSupportClassWithItsInterface.java
- src/main/resources/META-INF/rewrite/spring-boot-30.yml
As reported we missed including these recipes, even though Spring Batch 5 requires Java 17 & Spring Framework 6:
https://docs.spring.io/spring-batch/docs/5.0.6/reference/html/whatsnew.html#whatsNew
> Include Spring Batch in Spring Boot 3 upgrade

- src/main/resources/META-INF/rewrite/spring-framework-61.yml
Deprecated for removal in 6.1: Requests are now always streaming.
> as of 6.1 requests are always streamed, as if this property is {@code true}
https://github.com/spring-projects/spring-framework/blob/29dce74fcdd62c6c877973378368fe342afb5fbd/spring-web/src/main/java/org/springframework/http/client/SimpleClientHttpRequestFactory.java#L145-L148
> Remove `SimpleClientHttpRequestFactory.setOutputStreaming(boolean)` in SF 6.1

- build.gradle.kts
- src/main/resources/META-INF/rewrite/spring-boot-31.yml
- src/main/resources/META-INF/rewrite/spring-boot-32.yml
Spring boot upgrade to 3.2.4 also upgrades io.projectreactor/reactor-bom from 2020.0.27 to 2023.0.4. This in turn upgrades reactor-core module from 3.4.26 to 3.6.5.
@timtebeek
> Include new reactor migration as of springboot 3.2

- build.gradle.kts
- src/main/resources/META-INF/rewrite/spring-framework-60.yml
Include Apache HttpClient4 to HttpClient5 migration with Spring framework 6 migration 
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.1-Release-Notes#dependency-management-for-apache-httpclient-4
> Support for Apache HttpClient 4 with RestTemplate was [removed in Spring Framework 6](https://github.com/spring-projects/spring-framework/issues/28925), in favor of Apache HttpClient 5. Spring Boot 3.0 includes dependency management for both HttpClient 4 and 5. Applications that continue to use HttpClient 4 can experience [errors when using RestTemplate](https://github.com/spring-projects/spring-boot/issues/33515) that are difficult to diagnose.
> 
> Spring Boot 3.1 removes dependency management for HttpClient 4 to encourage users to move to HttpClient 5 instead.
> 
While …
> Include Apache Httpclient4 to 5 in Spring Framework 6 upgrade

- src/main/java/org/openrewrite/java/spring/framework/MigrateResponseStatusExceptionGetRawStatusCodeMethod.java
- src/main/resources/META-INF/rewrite/spring-framework-60.yml
- src/test/java/org/openrewrite/java/spring/framework/MigrateResponseStatusExceptionTest.java
Add recipe to migrate breaking changes introduced in Spring Framework 6.0 touching `ResponseStatusException` class. 
- https://github.com/openrewrite/rewrite-spring/issues/554
Was not sure where to put the recipes - I added them to `spring-framework-60.yml` as another group (? - let me know correct naming here)
> Add recipe to migrate `ResponseStatusException` changes

- src/main/java/org/openrewrite/java/spring/framework/MigrateResponseStatusExceptionGetStatusCodeMethod.java
- src/main/resources/META-INF/rewrite/spring-framework-60.yml
- src/test/java/org/openrewrite/java/spring/framework/MigrateResponseStatusExceptionTest.java
Address migration of `getStatus` to `getStatusCode` with respecting type change from `HttpStatus` to `HttpStatusCode`. 
- https://github.com/openrewrite/rewrite-spring/issues/554
> Migrate recipe to convert getStatus to getStatusCode with correct types

- src/main/resources/META-INF/rewrite/spring-boot-20.yml
@timtebeek 
Spring manages the version since boot2: https://github.com/spring-projects/spring-boot/blob/2.0.x/spring-boot-project/spring-boot-dependencies/pom.xml#L50
And not in 1.5: https://github.com/spring-projects/spring-boot/blob/1.5.x/spring-boot-dependencies/pom.xml
> Include Apache commons-lang3 migration with Spring Boot 2.0 ugprade

- src/main/resources/META-INF/rewrite/spring-boot-30.yml
Applies `jakarta.annotation-api` update recipe added here:
* https://github.com/openrewrite/rewrite-migrate-java/pull/579
@timtebeek 
Spring Boot 3 uses 2.1: https://github.com/spring-projects/spring-boot/blob/3.0.x/spring-boot-project/spring-boot-dependencies/build.gradle#L462-L468
Whereas Springboot 2.7 uses 1.3.5: https://github.com/spring-projects/spring-boot/blob/2.7.x/spring-boot-project/spring-boot-dependencies/build.gradle#L614-L624
> Include upgrading `jakarta.annotation-api` to 2.1.x

- src/main/resources/META-INF/rewrite/spring-boot-30.yml
this migrates SAP's cloud foundry based java logging support libraries to SB 3.x
SAP's cloud foundry based logging support on jakarta
See https://github.com/SAP/cf-java-logging-support/
make SB 3.x migrations with SAP and partner code easier
Questions:
- Does org.openrewrite.java.dependencies.ChangeDependency take care of maven AND gradle?
- I ONLY want to change the artifactId, NOT the groupId and the version or anything else - Does that fit?
- I saw no tests in this repo for pom.xml files, so I assume tests are in rewrite-maven/rewrite-gradle?
- Does this step ONLY kick in if the dependency com.sap.hcp.cf.logging:cf-java-logging-support-servlet:<someVersion> is present?
- Is this the right location to put the recipe in?
- The Mr. Monk in me did some formatting - is that OK?
> SAP cloud logging support migration to SB 3.x

- src/main/java/org/openrewrite/java/spring/framework/MigrateWebMvcConfigurerAdapter.java
- src/testWithSpringBoot_2_1/java/org/openrewrite/java/spring/framework/MigrateWebMvcConfigurerAdapterTest.java
The origin recipe only handle classes that extend WebMvcConfigurer. In some cases, people return `new WebMvcConfigurer()` directly as a bean.
- [✅] I've added unit tests to cover both positive and negative cases
- [✅] I've read and applied the [recipe conventions and best practices](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices)
- [✅] I've used the IntelliJ IDEA auto-formatter on affected files
> Add new migration case of WebMvcConfigurer

- src/main/java/org/openrewrite/java/spring/boot2/MigrateDatabaseCredentials.java
- src/main/java/org/openrewrite/java/spring/framework/MigrateHandlerInterceptor.java
- src/testWithSpringBoot_2_4/java/org/openrewrite/java/spring/MigrateHandlerInterceptorTest.java
Improve/Bugfix the `MigrateHandlerInterceptor`recipe to only migrate classes that directly extends the HandlerInterceptorAdapter.
Migration is targeted broadly, so it can migrate `super` calls when it is not intended to. This can lead to bugs, see 
- fixes https://github.com/openrewrite/rewrite-spring/issues/620
for example.
The migration does now convert `super.preHandle(..)` to `HandlerInterceptor.super.preHandle(..)`. According to mr [unconditional](https://stackoverflow.com/users/4571544/unconditional), you should migrate to `return true`. See [this](https://stackoverflow.com/questions/72152105/migrate-handlerinterceptor-to-spring-boot-2-6) SO post for more information.
_Also [this](https://sbrta.medium.com/spring-boot-2-to-3-a-migration-journey-92d5fb3a5b5b#7a20) blog seems to …
> MigrateHandlerInterceptor recipe migrates too much

- src/main/resources/META-INF/rewrite/spring-framework-53.yml
Fixes a reported issue about dependencies removed despite being used.
Didn't immediately spot any other RemoveDependency where we would want to add this conditional, as the others are part of a larger migration with code changes.
> Add `unlessUsing` to `RemoveDependency` to not break compilation

- build.gradle.kts
- src/main/resources/META-INF/rewrite/spring-boot-3-best-practices.yml
- src/main/resources/META-INF/rewrite/spring-boot-34.yml
- src/testWithSpringBoot_3_4/java/org/openrewrite/java/spring/boot3/SpringBootVersionUpgradeTest.java
- src/testWithSpringBoot_3_4/java/org/openrewrite/java/spring/boot3/testWithSpringBoot_3_4/java/org/openrewrite/java/spring/boot3/SpringCloudVersionUpgradeTest.java
Two changes
- Add a recipe for updating to Spring Boot 3.4.
- The Spring Boot 3 best practices recipe has been extracted from the Spring Boot 3.3 update recipe. 
- We don't have a recipe for Spring 6.2 yet, which I think should be part of the update.
- I have made the 3.4 upgrade part of the `org.openrewrite.java.spring.boot3.SpringBoot3BestPractices` recipe, as was the case with the 3.3 upgrade. However, since the recipe is now extracted/standalone do we still want this to be the case? 
@Laurens-W @timtebeek
> Add recipe for Spring Boot 3.4 migration

- src/main/java/org/openrewrite/java/spring/search/FindApiEndpoints.java
- src/main/java/org/openrewrite/java/spring/trait/SpringRequestMapping.java
- src/testWithSpringBoot_3_0/java/org/openrewrite/java/spring/search/FindApiEndpointsTest.java
The current logic did not cover the case where a `RequestMapping` with a path was defined on the Controller class, and no paths were defined in the `*Mapping` at the method level.
> Fix incorrect path computation for Spring API endpoints

- src/main/java/org/openrewrite/java/spring/RenameBean.java
Brief PR to restore the removed `fromDeclaration` static methods to allow for programmatic usage in custom recipes
> Restore Existing Static RenameBean Constructors

- src/main/resources/META-INF/rewrite/best-practices.yml
- src/main/resources/META-INF/rewrite/spring-boot-20.yml
- See #304 for exactly the same conversation :)
That said, getting philosophical:
I think we typically have a design pattern where "upgrades" and "best practices" are kept separate, and "best practices" allows for more opinionated/noisy changes. That's what the JUnit 5 recipes look like, iirc.
This file violates that pattern by having the 2.0 upgrade recipe include the best practices recipe. Buuuut, it's been that way for over a year, and the other included recipes aren't nearly as disruptive as this one.
I could imagine a spectrum with one extreme having only the most-strictly necessary changes, and the other end having the most noisy and least-popularly-agreed-upon changes, and we slice that spectrum into sections like:
- 1: "upgrades"
- 2: "best practices"
- 3: "standalone recipes"
- …
> Remove BeanMethodsNotPublic from SpringBoot2BestPractices (again)

- src/main/java/org/openrewrite/java/spring/security5/WebSecurityConfigurerAdapter.java
- src/testWithSpringSecurity_5_7/java/org/openrewrite/spring/security5/WebSecurityConfigurerAdapterTest.java
Currently al annotations on the class, when converting
```java
@Configuration
@AllOtherAnnotations
public static class SomeSecurityConfigurerAdapter extends WebSecurityConfigurerAdapter { .. }
```
to 
```java
@Bean
SecurityFilterChain someSecurityFilterChain(HttpSecurity http) throws Exception { .. }
```
, are dropped.
This PR lets them keep them:
```java
@Bean
@AllOtherAnnotations
SecurityFilterChain someSecurityFilterChain(HttpSecurity http) throws Exception { .. }
```
Just dropping the annotations can lead to serious bugs. For example, if a `@ConditionalOnProperty` annotation has been used, dropping it means different behaviour from the application.
> Keep annotations for merged classes for WebSecurityConfigurerAdapter recipe (Spring Security 5.4)

- src/main/resources/META-INF/rewrite/spring-framework-60.yml
The Assert.notEmpty(Collection<?> collection) was deprecated of 4.3.7, and removed in 6.1 in favor of Assert.notEmpty(Collection, String).
To prevent potential compilation errors during the upgrade to Spring Boot 3.3.X.
No.
No.
I don't think there is other workaround because this method will be removed in 6.1.
No.
No.
> Replace Assert.notEmpty(Collection<?> collection) with Assert.notEmpty(Collection<?> collection, String)

- src/main/java/org/openrewrite/java/spring/http/SimplifyWebTestClientCalls.java
- src/test/java/org/openrewrite/java/spring/http/SimplifyWebTestClientCallsTest.java
`SimplifyWebTestClientCalls` supports only int parameters for `isEqualTo` method.
This PR adds support for:
- `isEqualTo(HttpStatus.valueOf(200))`
- `isEqualTo(HttpStatusCode.valueOf(200))`
- `isEqualTo(HttpStatus.OK)`
Fix disabled test in `SimplifyWebTestClientCallsTest` and to be feature complete on this recipe.
Probably implementation can be improved but I am not yet familiar with OpenRewrite patterns.
none
> Add support for HttpStatus in SimplifyWebTestClientCalls

- src/main/resources/META-INF/rewrite/spring-boot-32.yml
In the Spring Boot 3.2 Upgrade Recipe the dependency `commons-codec:commons-code:1.7.x` was added even if transitively available.
Not overwrite other configuration from Dependency management.
> Fix transitivity handling for `commons-codec:commons-codec` in Spring Boot Update 3.2

- src/main/resources/META-INF/rewrite/spring-boot-20.yml
Replace deprecated `micrometer-spring-legacy` with `spring-boot-starter-actuator` when upgrading to Spring Boot 2.
- Fixes #673
It's a simple addition of just a yaml definition, but should there be tests?
> Replace micrometer-spring-legacy with spring-boot-starter-actuator

- src/main/resources/META-INF/rewrite/spring-security-57.yml
- src/main/resources/META-INF/rewrite/spring-security-58.yml
- src/main/resources/META-INF/rewrite/spring-security-60.yml
- src/main/resources/META-INF/rewrite/spring-security-61.yml
- src/main/resources/META-INF/rewrite/spring-security-63.yml
- src/testWithSpringSecurity_5_7/java/org/openrewrite/spring/security5/UpgradeSpringOauth2AuthorizationServerTest.java
Made `spring-security-oauth2-authorization-server` part of spring security upgrades
@timtebeek 
https://github.com/spring-projects/spring-authorization-server/releases
> Upgrade spring-security-oauth2-authorization-server

- src/main/resources/META-INF/rewrite/spring-boot-30.yml
Since PR https://github.com/openrewrite/rewrite-migrate-java/pull/674, the recipe JavaxMigrationToJakarta update to Jakarta 9 and not 10
Spring Boot 3 is Jakarta 10
None
None
No, it's the best option 😄 
No
> Spring Boot 3, Jakarta EE 9 regression

- src/main/java/org/openrewrite/java/spring/util/concurrent/SuccessFailureCallbackToBiConsumerVisitor.java
- src/test/java/org/openrewrite/java/spring/util/concurrent/ListenableToCompletableFutureTest.java
Handle a corner case of using `KafkaFailureCallback` in `ListenableFuture`
> Add KafkaFailureCallback handler

- src/main/java/org/openrewrite/java/spring/util/concurrent/SuccessFailureCallbackToBiConsumerVisitor.java
The method matcher can match the expressions that mockito mocking ListenableFuture and throws error.
If the first argument is a method invocation, very probably it's a `mockito.when()`, we should not do anything here.
For example:
```
ListenableFuture<SendResult> future = mock(ListenableFuture.class);
doAnswer(i -> {
return null;
}).when(future).whenComplete(any(), any());
```
> Add corner case of mockito on ListenableFuture

- src/main/java/org/openrewrite/java/spring/AddSpringProperty.java
- src/main/java/org/openrewrite/java/spring/boot2/ConvertToSecurityDslVisitor.java
- src/main/java/org/openrewrite/java/spring/boot2/MigrateDatabaseCredentials.java
- src/main/java/org/openrewrite/java/spring/data/JdbcTemplateQueryForLongMigration.java
- src/main/java/org/openrewrite/java/spring/table/ApiCalls.java
- src/main/java/org/openrewrite/java/spring/table/ApiEndpoints.java
- src/main/java/org/openrewrite/java/spring/table/SpringComponentRelationships.java
- src/main/java/org/openrewrite/java/spring/table/SpringComponents.java
Adapting code to changes in upstream constructors done in https://github.com/openrewrite/rewrite/pull/5324
Fix broken CI.
> Fix MergeYaml, J.Identifier, JavaType.Method constructor calls

- src/main/java/org/openrewrite/java/spring/batch/ConvertReceiveTypeWhenCallStepExecutionMethod.java
- src/testWithSpringBoot_3_0/java/org/openrewrite/java/spring/batch/ConvertReceiveTypeWhenCallStepExecutionMethodTest.java
Changing `ConvertReceiveTypeWhenCallStepExecutionMethod` not to visit references in Javadoc comments.
- fixes #702
> Exclude visiting Javadoc

- src/main/java/org/openrewrite/java/spring/boot2/MergeBootstrapYamlWithApplicationYaml.java
- src/testWithSpringBoot_2_4/java/org/openrewrite/java/spring/boot2/MergeBootstrapYamlWithApplicationYamlTest.java
There was a ClassCastException in this recipe when running on platform against some spring projects. 
The existing test was failing when I undo the disabling. Fixed the test, added some more tests + adapted the behaviour to correspond with the tests.
> Fixed the ClassCastException in MergeBootstrapYamlWithApplicationYaml recipe

- src/test/java/org/openrewrite/java/spring/kafka/RemoveUsingCompletableFutureTest.java
Fixing variable names in test cases.
Fixing broken CI after https://github.com/openrewrite/rewrite/pull/5454
> Fixing variable names in tests

- src/main/java/org/openrewrite/java/spring/ChangeSpringPropertyKey.java
- src/test/java/org/openrewrite/java/spring/ChangeSpringPropertyKeyTest.java
Also support `except` option and default values (as in `${foo:bar}`), including escaping (e.g. `${foo:\{bar\}}`).
Issues:
- #231
> Support `@Value` and `@ConditionalOnProperty` in `ChangeSpringPropertyKey`

- build.gradle.kts
- src/main/java/org/openrewrite/java/spring/doc/RemoveBeanValidatorPluginsConfiguration.java
- src/main/resources/META-INF/rewrite/springdoc.yml
- src/test/java/org/openrewrite/java/spring/doc/RemoveBeanValidatorPluginsConfigurationTest.java
Remove `@EnableSwagger2` and `@Import(BeanValidatorPluginsConfiguration.class)` when migration from Swagger to SpringDoc
Recipe was missing from the more general migration recipe.
> Remove unneeded annotation when migrating from Swagger to SpringDoc

- src/main/resources/META-INF/rewrite/spring-boot-30.yml
- src/main/resources/META-INF/rewrite/spring-boot-31.yml
- src/main/resources/META-INF/rewrite/spring-boot-32.yml
- src/main/resources/META-INF/rewrite/spring-boot-33.yml
- src/main/resources/META-INF/rewrite/spring-boot-34.yml
- src/main/resources/META-INF/rewrite/springdoc.yml
Split up the Springdoc migration recipes
Upgrade according to the compatibility matrix posted here:
https://springdoc.org/#what-is-the-compatibility-matrix-of-springdoc-openapi-with-spring-boot
Spring Boot Versions | Springdoc OpenAPI Versions
-- | --
3.4.x | 2.7.x - 2.8.x
3.3.x | 2.6.x
3.2.x | 2.3.x - 2.5.x
3.1.x | 2.2.x
3.0.x | 2.0.x - 2.1.x
2.7.x, 1.5.x | 1.6.0+
2.6.x, 1.5.x | 1.6.0+
2.5.x, 1.5.x | 1.5.9+
2.4.x, 1.5.x | 1.5.0+
2.3.x, 1.5.x | 1.4.0+
2.2.x, 1.5.x | 1.2.1+
2.0.x, 1.5.x | 1.0.0+
Reported on https://stackoverflow.com/questions/79667881/classnotfoundexception-org-springframework-web-servlet-resource-litewebjarsreso
> Use springdoc compatibility matrix

- src/main/resources/META-INF/rewrite/replace-mock-and-spybean.yml
- src/testWithSpringBoot_3_4/java/org/openrewrite/java/spring/boot3/ReplaceMockBeanAndSpyBeanTest.java
> Fix package for `MockReset` once migrating SpyBean/MockBean to MockitoSpyBean/MockitoBean

- src/main/java/org/openrewrite/java/spring/boot2/MergeBootstrapYamlWithApplicationYaml.java
- src/main/java/org/openrewrite/java/spring/boot2/MigrateDatabaseCredentialsForToolYaml.java
> Moving away from deprecated no-args constructor for `CoalesceProperties` and its visitor

- src/main/java/org/openrewrite/java/spring/kafka/KafkaTestUtilsDuration.java
- src/test/java/org/openrewrite/java/spring/kafka/KafkaTestUtilsDurationTest.java
The test that I added showed that the template was wrong: 
```
java.lang.IllegalArgumentException: Template parameter 0 cannot be used in an untyped template substitution. Instead of "#{}", indicate the template parameter's type with "#{any(long)}".
org.openrewrite.java.internal.template.Substitutions.substituteUntyped(Substitutions.java:183)
org.openrewrite.java.internal.template.Substitutions.lambda$substitute$0(Substitutions.java:83)
org.openrewrite.internal.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:98)
org.openrewrite.internal.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:74)
org.openrewrite.java.internal.template.Substitutions.substitute(Substitutions.java:61)
org.openrewrite.java.JavaTemplate.apply(JavaTemplate.java:115) …
```
> Fix bug where KafkaTestUtils duration argument can be something else then a J.Literal
